### ISSUE TITLE
Pipeline coloring refresh

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#78]
Update of the editor is not working properly. Defined color is not taken over, but on mouse hover. Please check!!!

Follow-up of #9

**Comment by Nowatzki** [comment]
My current tests are working. I checked a color-change from red to green to orange.

**Comment by eichelbe** [comment]
Did you try against a running pipeline?

**Comment by Nowatzki** [comment]
No I did not because I cant do that on my pc at home. I simulated sth. like a running pipeline and reset statuses several times. Thats not a "real" pipeline, but it assures that the Pipeline-Status is working as it should. Icons are taken over right after validation and in potentially open editor. "Hover over bug" is solved!
