### ISSUE TITLE
Display multiple runtime graphs

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#83]
In addition to the single runtime graph based on the observables mapping (see #81)
- allow displaying further graphs on user selection on pipeline level
- allow displaying further graphs on user selection of pipeline element level

Reuse existing code - refactor so that observable / element / pipeline can be specified.
Think about whether a view or a floating dialog is more appropriate.

**Comment by eichelbe** [comment]
I know about ongoing testing, but what is the actual status?

**Comment by Nowatzki** [comment]
Currently the RuntimeView is able to display mutliple Pipelinetraces based on the chosen pipeline-elements and QM-Observables.

What is missing:
- The setting of chosen colors per trace is not supported yet.
- While closing the editor the last user selections shall be saved as metadata in order to load them with the editors next reopening. Testing will show whether this behavior is suitable for the contemplated interface.

Several ui-improvements may be discussed later on.

**Comment by eichelbe** [comment]
What's happening here?

**Comment by Nowatzki** [comment]
The setting of user-selected color per trace is working now. The last thing missing is the storing and loading of user selections if you still need that.^^ This is the last thing on my list and I already discussed with Sascha whether we should use a simple textfile or serializing for such data. I will solve this issue next week. All in all the Runtimeeditor is nearly done.

**Comment by eichelbe** [comment]
Basically done, enhancements filed as issues...
