### ISSUE TITLE
Instantiate / optimize model for runtime

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#88]
-> instead of copying the model, perform
- constraint pruning
- prune unused familes
- freeze (instead of unfreeze)
- additional: serialize
-> deploy

VIL operators/instantiators would be nice, if too much effort, add a QM-specific instantiator to QM-Extension

**Comment by Elscha** [comment]
It is now possible to create a deep copy of the model, including an instantiated configuration. This can be done with the `ProjectCopyVisitor`. The copied model be frozen dynamically and also be pruned, using the `ProjectRewriteVisitor`.
However, still open are:

- Further prunings/opimizations for runtime reasoning.
- Buildmodel must load the copied model. Otherwise, values of custom data types will force the instantation to crash.

This function can be activated via `de.uni_hildesheim.sse.qmApp.commands.AbstractInstantiateLocal.PRUNE_CONFIG`

**Comment by Elscha** [comment]
Updated starting comment accroding to 35c0fda. ModelModification is active and emcompasses the following:

- ModelPruning (active)
- Usage of modified model for instantiation (active)
- Using the modified model as source reference in build script, to publish the modified model (active)
- Freezeing the model (**inactive**)

**Comment by Elscha** [comment]
Model freezing still not activated. However, this should not affect the functionality of the tool.
This won't be done in the context of QualiMaster.
